apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-smi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://linkerd.github.io/linkerd-smi
    chart: linkerd-smi
    targetRevision: 1.1.2 # Điều chỉnh version nếu cần
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-smi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
