apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/thuanthentran/dqn-lstm-agent-driven-canary-release'
    targetRevision: linkerd
    path: gitops/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/thuanthentran/dqn-lstm-agent-driven-canary-release'
    targetRevision: linkerd
    path: gitops/charts/bootstrap
    helm:
      parameters:
        - name: global.destinationNamespace
          value: prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-twin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/thuanthentran/dqn-lstm-agent-driven-canary-release'
    targetRevision: linkerd
    path: gitops/charts/bootstrap
    helm:
      parameters:
        - name: global.destinationNamespace
          value: twin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
