apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
data:
  rollout-controller-config: |
    trafficRoutingPlugins:
      argoproj-labs/gatewayAPI:
        command: /plugins/gatewayapi-plugin-linux-amd64
        args: ["-log-level", "debug"]
