apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/crd-servicemonitors.yaml
  - crds/trafficsplit-crd.yaml
  - agent/agent-crd.yaml
  - agent/agent-operator.yaml
  - agent/agent-instance.yaml
  - argo-rollouts/argo-rollouts-namespace.yaml
  - argo-rollouts/argo-rollouts-install.yaml
  - argo-rollouts/argo-rollouts-config.yaml
  - argo-rollouts/argo-rollouts-rbac.yaml
