apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/crd-servicemonitors.yaml
  - namespaces/prod-namespace.yaml
  - namespaces/twin-namespace.yaml
  - agent/agent-crd.yaml
  - agent/agent-operator.yaml
  - agent/agent-instance.yaml
  - agent/agent-rbac.yaml
  - agent/agent-nodeport-svc.yaml
  - argo-rollouts/argo-rollouts-namespace.yaml
  - argo-rollouts/argo-rollouts-install.yaml
  - argo-rollouts/argo-rollouts-config.yaml
  - argo-rollouts/argo-rollouts-rbac.yaml
  - redis-cart/redis-cart.yaml
  - sync-controller/sync-controller.yaml
