apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: universal-rl-agent-eval
  namespace: default
spec:
  # Cấu hình 3 tham số động sẽ được Rollout truyền vào
  args:
  - name: service-name
  - name: stable-hash
  - name: canary-hash
  metrics:
  - name: rl-agent-decision
    # Sử dụng Webhook để đấm thẳng vào API của Agent
    provider:
      web:
        url: "http://agent-service.default.svc.cluster.local:8000/api/v1/decision"
        method: POST
        # Gói tên service và mã hash thành JSON gửi cho Agent
        jsonBody:
          service: "{{args.service-name}}"
          stable_hash: "{{args.stable-hash}}"
          canary_hash: "{{args.canary-hash}}"
    # Thành công khi API trả về biến action = 1 (Promote)
    successCondition: result.action == 1 
    # Thất bại (Rollback) khi API trả về action = 0
    failureCondition: result.action == 0