apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-ai-agent
  namespace: default
  labels:
    app: canary-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-ai-agent
  template:
    metadata:
      labels:
        app: canary-ai-agent
    spec:
      containers:
      - name: ai-agent
        image: ghcr.io/thuanthentran/dqn-lstm-agent-driven-canary-release/canary-ai-service:aa9f7ad
        env:
        - name: MODEL_PATH
          value: models/model_canary_drqn.pth
        - name: PROMETHEUS_URL
          value: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
---
apiVersion: v1
kind: Service
metadata:
  name: canary-ai-agent-svc
  namespace: default
spec:
  selector:
    app: canary-ai-agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000