apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-ai-agent
  labels:
    app: canary-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-ai-agent
  template:
    metadata:
      labels:
        app: canary-ai-agent
    spec:
      containers:
      - name: ai-agent
        image: ghcr.io/thuanthentran/dqn-lstm-agent-driven-canary-release/canary-ai-service:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: canary-ai-agent-svc
spec:
  selector:
    app: canary-ai-agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000