apiVersion: v1
kind: Node
metadata:
  name: kwok-node-01
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: "true"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-node-01
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
spec:
  # HÀNG RÀO BẢO VỆ: Cấm Pod thật nhảy vào đây
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: "true"