apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.3.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            # QUAN TRỌNG: Cho phép Prometheus tự động tìm kiếm PodMonitor ở mọi namespace
            # dù có hay không có release label khớp với tên chart.
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: "local-path"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
          service:
            type: NodePort
        
        grafana:
          initChownData:
            enabled: false
          podSecurityContext:
            fsGroup: 472
            runAsGroup: 472
            runAsUser: 472
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: "local-path"
          service:
            type: NodePort
          
          # TỰ ĐỘNG IMPORT ISTIO DASHBOARDS
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'istio'
                orgId: 1
                folder: 'Istio'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/istio
          dashboards:
            istio:
              istio-mesh:
                url: https://raw.githubusercontent.com/istio/istio/master/manifests/addons/dashboards/istio-mesh-dashboard.json
              istio-service:
                url: https://raw.githubusercontent.com/istio/istio/master/manifests/addons/dashboards/istio-service-dashboard.json
              istio-workload:
                url: https://raw.githubusercontent.com/istio/istio/master/manifests/addons/dashboards/istio-workload-dashboard.json

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
