apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-release
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: my-app
          image: ghcr.io/thuanthentran/dqn-lstm-agent-driven-canary-release/my-app:3e8cf2a
          env:
            - name: APP_SCENARIO
              value: "cpu_spike"
            - name: APP_VERSION
              value: "v4.0.0"
          ports:
            - name: http
              containerPort: 8080

  strategy:
    canary:
      dynamicStableScale: true
      maxSurge: 1
      maxUnavailable: 0
      canaryService: my-app-canary
      stableService: my-app-stable
      trafficRouting:
        nginx:
          stableIngress: my-app-ingress
      analysis:
        successfulRunHistoryLimit: 1    # Chỉ giữ lại 1 AnalysisRun thành công gần nhất
        unsuccessfulRunHistoryLimit: 2  # Giữ lại 2 cái thất bại/inconclusive để còn debug

      # KHỐI STEPS ĐÃ ĐƯỢC THỤT LÙI VÀO TRONG CANARY:
      steps:
        # Giai đoạn thăm dò (Tăng chậm, rủi ro cao)
        - setWeight: 10
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "10"}]

        - setWeight: 20
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "20"}]

        - setWeight: 30
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "30"}]

        - setWeight: 40
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "40"}]

        - setWeight: 50
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "50"}]

        # Giai đoạn tăng tốc (Nếu qua được 50% thì thường là đã ổn)
        - setWeight: 60
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "60"}]

        - setWeight: 80
        - analysis:
            templates: [{templateName: ai-dqn-decision}]
            args: [{name: rollout-name, value: "my-app-v2"}, {name: target-weight, value: "80"}]

        - setWeight: 100
