apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  # Tên Rollout sẽ tự động lấy theo tên service (vd: paymentservice)
  name: {{ .Values.serviceName }}
  namespace: default
spec:
  # Tự động lấy số lượng replicas gán tĩnh từ file values (Ví dụ: 5 pods)
  replicas: {{ .Values.replicas | default 1 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: server
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.containerPort }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }} # <--- Chỉ giữ lại 1 end này cho vòng lặp range

  strategy:
    canary:
      canaryService: {{ .Values.serviceName }}-canary
      stableService: {{ .Values.serviceName }}-stable
      
      # PATCH: Chuyển từ Gateway API sang SMI cho Linkerd
      trafficRouting:
        smi:
          rootService: {{ .Values.serviceName }}
          trafficSplitName: {{ .Values.serviceName }}-split
            
      steps:
      - setWeight: 20
      - analysis:
          templates:
          - templateName: universal-rl-agent-eval
          args:
          - name: service-name
            value: {{ .Values.serviceName }}
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: target-weight
            value: "20"
      - setWeight: 50
      - analysis:
          templates:
          - templateName: universal-rl-agent-eval
          args:
          - name: service-name
            value: {{ .Values.serviceName }}
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: target-weight
            value: "50"
      - setWeight: 80
      - analysis:
          templates:
          - templateName: universal-rl-agent-eval
          args:
          - name: service-name
            value: {{ .Values.serviceName }}
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: target-weight
            value: "80"