serviceName: adservice
replicas: 1
image: ghcr.io/thuanthentran/adservice:latest
containerPort: 9555
portName: grpc
env:
  - name: PORT
    value: "9555"
  - name: DISABLE_PROFILER
    value: "1"
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 15
  grpc:
    port: 9555
