serviceName: frontend
replicas: 1
image: ghcr.io/thuanthentran/frontend:latest
containerPort: 8080
portName: http
serviceType: NodePort   # <--- Thêm type NodePort
nodePort: 30080
env:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "cilium-gateway-productcatalogservice-gateway:80"
  - name: CURRENCY_SERVICE_ADDR
    value: "cilium-gateway-currencyservice-gateway:80"
  - name: CART_SERVICE_ADDR
    value: "cilium-gateway-cartservice-gateway:80"
  - name: RECOMMENDATION_SERVICE_ADDR
    value: "cilium-gateway-recommendationservice-gateway:80"
  - name: SHIPPING_SERVICE_ADDR
    value: "cilium-gateway-shippingservice-gateway:80"
  - name: CHECKOUT_SERVICE_ADDR
    value: "cilium-gateway-checkoutservice-gateway:80"
  - name: AD_SERVICE_ADDR
    value: "cilium-gateway-adservice-gateway:80"
  - name: ENABLE_PROFILER
    value: "0"
  - name: SHOPPING_ASSISTANT_SERVICE_ADDR
    value: "dummy-shoppingassistant.default.svc.cluster.local:80"
  