serviceName: frontend
replicas: 1
image: ghcr.io/thuanthentran/frontend:latest
containerPort: 8080
portName: http
env:
  - name: PORT
    value: "8080"
  - name: CHECKOUT_SERVICE_ADDR
    value: "checkoutservice:5050"
  
