serviceName: frontend
replicas: 1
image: ghcr.io/thuanthentran/samplemicroservice:latest
containerPort: 8000
portName: http
env:
  - name: SERVICE_NAME
    value: frontend
  - name: UPSTREAMS
    value: http://service-a:8000,http://service-b:8000
