serviceName: loadgenerator
replicas: 1
image: ghcr.io/thuanthentran/loadgenerator:44a4660479d4ffcda99f18067732e1395665328d
isLoadGenerator: true
containerPort: 0
portName: none
env:
  - name: FRONTEND_ADDR
    value: "frontend:8080"
  - name: USERS
    value: "10"
