serviceName: paymentservice
replicas: 1
image: ghcr.io/thuanthentran/paymentservice:df41014bdcfcec78cc5d92acf9c301d627e56e79
containerPort: 50051
portName: grpc
env:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"
readinessProbe:
  initialDelaySeconds: 20
  grpc:
    port: 50051
