serviceName: productcatalogservice
replicas: 1
image: ghcr.io/thuanthentran/productcatalogservice:44a4660479d4ffcda99f18067732e1395665328d
containerPort: 3550
portName: grpc
env:
  - name: PORT
    value: "3550"
  - name: DISABLE_PROFILER
    value: "1"
readinessProbe:
  initialDelaySeconds: 20
  grpc:
    port: 3550
