serviceName: service-b
replicas: 1
image: ghcr.io/thuanthentran/samplemicroservice:latest
containerPort: 8000
portName: http
env:
  - name: SERVICE_NAME
    value: service-b
  - name: UPSTREAMS
    value: ""

