serviceName: service-b
replicas: 1
image: ghcr.io/thuanthentran/samplemicroservice:latest
containerPort: 8000
portName: http
env:
  - name: SERVICE_NAME
    value: service-b
  - name: UPSTREAMS
    value: ""
  - name: CHAOS_DELAY_MS
    value: "100"

extraVolumes:
  - name: config-volume
    configMap:
      name: service-b-configmap

extraVolumeMounts:
  - name: config-volume
    mountPath: /app/main.py
    subPath: main.py
