serviceName: shippingservice
replicas: 1
image: ghcr.io/thuanthentran/shippingservice:44a4660479d4ffcda99f18067732e1395665328d
containerPort: 50051
portName: grpc
env:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"
readinessProbe:
  initialDelaySeconds: 20
  grpc:
    port: 50051
