"""
Visualize results comparing RL Agent vs Rule-based Controller.
Reads real data from 'results_final/' generated by the benchmark framework.

Usage:
  python3 scripts/visualize.py
"""

import argparse
import glob
import json
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def load_run_data(result_dir: str):
    """Load metrics.csv and timeline.json from a run directory."""
    if not os.path.exists(result_dir):
        return None, None
        
    metrics_file = os.path.join(result_dir, "metrics.csv")
    timeline_file = os.path.join(result_dir, "timeline.json")
    
    if not os.path.exists(metrics_file) or not os.path.exists(timeline_file):
        return None, None
        
    df = pd.read_csv(metrics_file)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    with open(timeline_file, 'r') as f:
        timeline = json.load(f)
        
    return df, timeline

def align_and_aggregate_runs(run_dirs: list):
    """Aligns multiple runs by fault_inject_time (t=0) and aggregates them."""
    aligned_dfs = []
    
    for rd in run_dirs:
        df, timeline = load_run_data(rd)
        if df is None or len(df) == 0:
            continue
            
        fault_time = pd.to_datetime(timeline["fault_inject_time"])
        # Calculate relative time in seconds from fault injection
        df['relative_time'] = (df['timestamp'] - fault_time).dt.total_seconds()
        
        # We need a common time grid to aggregate multiple runs.
        # Since scrape interval is 15s, we round to nearest 15s grid.
        df['time_grid'] = (df['relative_time'] / 15).round() * 15
        
        # Remove duplicates on time grid
        df = df.drop_duplicates(subset=['time_grid'])
        df = df.set_index('time_grid')
        
        aligned_dfs.append(df)
        
    if not aligned_dfs:
        return None
        
    # Aggregate (mean and std)
    concat_df = pd.concat(aligned_dfs)
    mean_df = concat_df.groupby(concat_df.index).mean()
    std_df = concat_df.groupby(concat_df.index).std().fillna(0)
    
    # Also return the average rollback time
    rollback_times = []
    for rd in run_dirs:
        _, timeline = load_run_data(rd)
        t_inject = pd.to_datetime(timeline["fault_inject_time"])
        if "first_rollback_step" in timeline and timeline["first_rollback_step"] is not None:
            # Reconstruct when rollback happened
            with open(os.path.join(rd, "action_log.json")) as f:
                actions = json.load(f)
            for a in actions:
                if a.get("action") == 2: # ROLLBACK
                    t_rollback = pd.to_datetime(a["timestamp"])
                    rollback_times.append((t_rollback - t_inject).total_seconds())
                    break
                    
    avg_rollback = np.mean(rollback_times) if rollback_times else None
    
    return mean_df, std_df, avg_rollback

def plot_scenario_comparison(scenario_name: str, base_dir: str, out_dir: str):
    print(f"Plotting {scenario_name}...")
    
    rl_dirs = glob.glob(os.path.join(base_dir, f"{scenario_name}-rl_agent-*"))
    rb_dirs = glob.glob(os.path.join(base_dir, f"{scenario_name}-rule_based_static-*"))
    
    rl_data = align_and_aggregate_runs(rl_dirs)
    rb_data = align_and_aggregate_runs(rb_dirs)
    
    if not rl_data and not rb_data:
        print(f"  Skipping {scenario_name}: No data found.")
        return
        
    fig, axes = plt.subplots(3, 1, figsize=(12, 12), sharex=True)
    fig.suptitle(f'Canary Rollout Comparison: RL Agent vs Rule-based\nScenario: {scenario_name}', fontsize=16)
    
    # Define plotting helper
    def plot_metric(ax, df_mean, df_std, metric, color, label):
        if df_mean is None or metric not in df_mean.columns: return
        t = df_mean.index
        y = df_mean[metric]
        y_err = df_std[metric]
        ax.plot(t, y, label=label, color=color, linewidth=2.5)
        ax.fill_between(t, np.maximum(0, y - y_err), y + y_err, color=color, alpha=0.2)
        
    for i, ax in enumerate(axes):
        ax.axvline(x=0, color='black', linestyle=':', label='Fault Injected')
        
        # Plot Rollback times
        if rl_data and rl_data[2] is not None:
            ax.axvline(x=rl_data[2], color='blue', linestyle='-.', alpha=0.7, label='RL Rollback')
        if rb_data and rb_data[2] is not None:
            ax.axvline(x=rb_data[2], color='red', linestyle='-.', alpha=0.7, label='Rule-based Rollback')
            
        if rl_data:
            df_mean, df_std, _ = rl_data
            if i == 0: plot_metric(ax, df_mean, df_std, 'canary_error_rate', 'blue', 'RL Agent')
            elif i == 1: plot_metric(ax, df_mean, df_std, 'canary_p95_latency', 'blue', 'RL Agent')
            elif i == 2: plot_metric(ax, df_mean, df_std, 'traffic_weight_canary', 'blue', 'RL Agent Weight')
            
        if rb_data:
            df_mean, df_std, _ = rb_data
            if i == 0: plot_metric(ax, df_mean, df_std, 'canary_error_rate', 'red', 'Rule-based')
            elif i == 1: plot_metric(ax, df_mean, df_std, 'canary_p95_latency', 'red', 'Rule-based')
            elif i == 2: plot_metric(ax, df_mean, df_std, 'traffic_weight_canary', 'red', 'Rule-based Weight')

        if i == 0:
            ax.set_ylabel('Error Rate')
            ax.set_title('Error Rate vs Time')
            ax.legend(loc='upper right')
        elif i == 1:
            ax.set_ylabel('P95 Latency (ms)')
            ax.set_title('P95 Latency vs Time')
        elif i == 2:
            ax.set_xlabel('Time from Fault Injection (seconds)')
            ax.set_ylabel('Canary Traffic Weight')
            ax.set_title('Traffic Weight')
            
        ax.grid(True)
        ax.set_xlim(-60, 150) # Focus window

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    
    out_file = os.path.join(out_dir, f"{scenario_name}_comparison.png")
    os.makedirs(out_dir, exist_ok=True)
    plt.savefig(out_file)
    plt.close()
    print(f"  Saved {out_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--result-dir", default="results_final")
    parser.add_argument("--out-dir", default="results")
    args = parser.parse_args()
    
    scenarios = [
        "S1_high_latency",
        "S2_cpu_spike",
        "S3_memory_leak",
        "S4_error_burst",
        "S5_cascading_failure"
    ]
    for s in scenarios:
        plot_scenario_comparison(s, args.result_dir, args.out_dir)
