name: Build All Microservices

on:
  push:
    branches: 
      - OffTrain
  workflow_dispatch: # Thêm cái này để test tay

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [checkoutservice]
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
