name: Build and Push All Microservices

on:
  push:
    branches: [ "OffTrain" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # BẮT BUỘC: Cấp quyền ghi vào Registry

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [adservice, cartservice, checkoutservice, currencyservice, emailservice, frontend, loadgenerator, paymentservice, productcatalogservice, recommendationservice, shippingservice] # Thêm các service khác vào đây
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Dùng token mặc định của GitHub

      - name: Prepare Image Name
        id: prep
        run: |
          # GHCR yêu cầu tên image phải viết thường
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}
          echo "image_name=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/src/${{ matrix.service }}
          push: true
          tags: ${{ steps.prep.outputs.image_name }}:latest