name: Build and Push Microservices

on:
  push:
    branches: [ "linkerd" ]
    paths:
      - 'services/src/samplemicroservice/**'
      - 'services/agent/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Image Names
        id: prep
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/samplemicroservice
          echo "image_name=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT
          AGENT_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/agent
          echo "agent_image_name=${AGENT_IMAGE_NAME,,}" >> $GITHUB_OUTPUT

      - name: Build and push samplemicroservice
        uses: docker/build-push-action@v4
        with:
          context: ./services/src/samplemicroservice
          file: ./services/src/samplemicroservice/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.image_name }}:latest

      - name: Build and push agent
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./services/agent/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.agent_image_name }}:latest